[tool.poetry]
name = "django-starter-kit"
version = "0.1.0"
description = ""
authors = ["Junte Ltd <tech@junte.ru>"]

[tool.poetry.dependencies]
python = "^3.6"
cookiecutter = "^1.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
